name:  movie-analyst-ui-CI

on:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'

workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
      
  test:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - run: npm test

  build-and-push:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Build and push develop
        if: github.ref == 'refs/heads/develop'
        id: docker_build_develop
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: juancastaneda20/${{ env.IMAGE_NAME }}:develop
      -
        name: Build and push master
        if: github.ref == 'refs/heads/master'
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: juancastaneda20/${{ env.IMAGE_NAME }}:latest,juancastaneda20/${{ env.IMAGE_NAME }}:latest 
      -
        name: Retag images and push
        if: github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/staging'
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: juancastaneda20/${{ env.IMAGE_NAME }}:develop
          dst: juancastaneda20/${{ env.IMAGE_NAME }}:qa